### ISSUE TITLE
.Net Core Socket ConnectAsync

### ISSUE THREAD

**Issue by ngonzalezromero** [9swampy/Telnet#11]
I trying port the library to net core..
but I found only one problem

in TcpClient.cs class, the net core socket  constructor does not take parameters
so, i made this change

          public TcpClient(string hostName, int port)
          {
            this.client = new System.Net.Sockets.TcpClient();
            this.client.ConnectAsync(hostName, port).GetAwaiter().GetResult();
          }

but I think that is not the correct way, because I calling a async method in a sync context

What is the best way to call this new method?
cc @9swampy

**Comment by 9swampy** [comment]
I've not done much with NetCore to date but that does smell a bit, I agree. I'd probably go down the route of storing the hostName and port and executing the connect only when it's needed.

Do push up your work in progress on a feature branch off develop. It's always easier to see the code in context.

**Comment by ngonzalezromero** [comment]
@9swampy 
https://github.com/ngonzalezromero/Telnet
I sent the PR too

**Comment by opeyemiowolabi** [comment]
Please how do i get a sample implementation for the library.
What i really intend to do is to programmatic logon to the server, and start issuing series of request/responses.

Thankyou

**Comment by 9swampy** [comment]
There's a sample on the README.md that does exactly that; only using the dummy server used in the UnitTests.

**Comment by 9swampy** [comment]
So I've merged rweads0520 pull request and his comment:
> 
    public TcpClient(string hostName, int port)
    {
    #if NET451
      this.client = new System.Net.Sockets.TcpClient(hostName, port);
    #else
      this.client = new System.Net.Sockets.TcpClient();
      // .NetStandard does not include a synchronous constructor or Connect method.
      // This will normally not be connected by the time the constructor returns,
      // it is the responsibility of the caller to ensure that they wait for the
      // connection to complete or fail, using this.Connected.
      // The PrimS.Telnet.Client constructor does this.
      // Adding something awaitable on this class to connect or wait for connection
      // would break backward compatibility and require a lot of refactoring.
      // This will do for now.
      var nowait = client.ConnectAsync(hostName, port);
    #endif
    }`

I've got some learning in the Net.Standard space to do. Will keep this issue open and try find time to revisit if it continues to cause issues.
