### ISSUE TITLE
Connection reset when called TryLogin() on Cisco 2504

### ISSUE THREAD

**Issue by matsujirushi** [9swampy/Telnet#14]
I try this library to connect a Cisco 2504(Wireless LAN Controller).
To be disconncted when called TryLogin().

'Raw mode will not be supported, Closing connection.'

**Comment by 9swampy** [comment]
Very happy to roll in a fix if you submit and it doesn't break anything :)

**Comment by matsujirushi** [comment]
Changing the next two allowed us to communicate with Cisco 2504.

1. Single packet of ReplyToCommand bytes
2. Respond "do echo" to "will echo"

I modified code and it's fine.
https://github.com/matsujirushi/Telnet/commit/e569f0dcca38a57f565b6d9bc8d89be3449a8617

But ASYNC not implement.

Please advice.

**Comment by 9swampy** [comment]
Great that it works in your scenario but I don't think it's right to reply "will echo" when we won't be? However knowing there's an issue, Cisco's are pretty common and presumably it's a shared issue and you've a workaround I'd be keen to find a way to build in your fix. Pity I don't have Cisco units to play with...

**Comment by 9swampy** [comment]
FWIW latest versions have rolled in an equivalent fix in [ReplyToCommand](https://github.com/9swampy/Telnet/blob/d72ed7c470126c650e7c438773dffaea323e0ff7/PrimS.Telnet.NetStandard/ByteStreamHandler.cs#L349). . .
