### ISSUE TITLE
How to send Ctrl C upon logging in

### ISSUE THREAD

**Issue by akeilox** [9swampy/Telnet#16]
I have a device with root telnet login but it executes a script every time I login to it.

Is there any way to send CTRL C command upon login?

My use case is very simple, I need to execute command reboot and exit, but will be doing this from asp.net

**Comment by 9swampy** [comment]
It will depend on your environment what you'll need to send and how you'd do it. I'd suggest you search for e.g. "send ctrl c over telnet" for a wealth of suggestions. I don't think there's any reason why you wouldn't be able to using the library. I'd be happy to hear how you get it to work and integrate a PR if necessary...
