### ISSUE TITLE
Can't log in to the linux telnetd

### ISSUE THREAD

**Issue by Nerus87** [9swampy/Telnet#17]
As in topic, I can't log into the Linux telnet server via C#, but I can log in via Putty which same login and password.

```
using (Client client = new Client("10.0.0.249", 23, new CancellationToken()))
{
	if (client.IsConnected)
	{
		Console.WriteLine($"Connected to the telnet server.");

		bool result = await client.TryLoginAsync("test", "test", 2000);
	
		if (result)
			Console.WriteLine($"Loginedin as test.");
		else
			Console.WriteLine($"Loginedin failed.");
	}
	else
		Console.WriteLine($"Can't connect to the telnet server.");
}
```

**Result**: after 2s "Loginedin: failed."

Is that project it is for specific telnet server ?!

**Comment by 9swampy** [comment]
No, it's generic. What version are you using? The NetStandard version wouldn't pass the client.IsConnected check you've in your code; see [here ](https://github.com/9swampy/Telnet/issues/11).

**Comment by 9swampy** [comment]
> public async Task<bool> TryLoginAsync(string username, string password, int loginTimeoutMs)
{
  bool result = await this.TrySendUsernameAndPassword(username, password, loginTimeoutMs);
  if (result)
  {
     result = await this.IsTerminatedWith(loginTimeoutMs, ">");
  }
  return result;
  }

When you log in via Putty can you see the line terminates with a ">"? If not perhaps you could refactor to accept the terminator as an extra parameter?
