### ISSUE TITLE
TryLoginAsync

### ISSUE THREAD

**Issue by nertilpoci** [9swampy/Telnet#19]
TryLoginAsync() is returning always false 
Thanks

**Comment by 9swampy** [comment]
You may find clarification in #5 

Alternatively can you confirm the terminating character when you telnet in is the ">" expected in your specific scenario? What package/specific library are you using?

**Comment by nertilpoci** [comment]
Thanks i checked the code now and it is looking by default for ":" to be terminated with. I was looking for a general method to check against multiple telnet clients whose terminating string i do not know. 
Thanks for the clarification, and keep up the good work

**Comment by 9swampy** [comment]
No reason you couldn't make the calls to the log in yourself instead of using the Login wrapper that just makes two responses for terminated read calls; you could make those as generic as you like.

**Comment by nertilpoci** [comment]
Yes i am doing it that way now.
thank you
