### ISSUE TITLE
Can not be used according to "usage"

### ISSUE THREAD

**Issue by derekdonyen** [9swampy/Telnet#20]
I am a novice using c # to develop telnet-related apps.
And I used the VS2012 installed this API, but I can't understand how to use it after i read the "Usage" many times. I think the Usage is pseudo code not really example.
Because of I copy paste the sample code(in the usage) into VS2012 there are some error happened.
There are some properties and methods that can not be found.(TelnetServer、.Should().Be(true))
Could you kindly tell me or give me some really example let me know how to use this API.
Many thanks.

**Comment by 9swampy** [comment]
It's not pseudo code, but it is an incomplete example as the example as is requires some imports. Combine the headers in https://github.com/9swampy/Telnet/blob/master/PrimS.Telnet.CiTests/WithClient.cs with the full code of the last ReadMeExample method in the aforementioned file and that should get you going again.
