### ISSUE TITLE
We don't handle common TELNET codes

### ISSUE THREAD

**Issue by A9G-Data-Droid** [9swampy/Telnet#32]
The following codes should be handled instead of treated like printable characters.

From RFC854:

>          BELL (BEL)              7      Produces an audible or
>                                         visible signal (which does
>                                         NOT move the print head).
>          Back Space (BS)         8      Moves the print head one
>                                         character position towards
>                                         the left margin.
>          Horizontal Tab (HT)     9      Moves the printer to the
>                                         next horizontal tab stop.
>                                         It remains unspecified how
>                                         either party determines or
>                                         establishes where such tab
>                                         stops are located.
>          Vertical Tab (VT)       11     Moves the printer to the
>                                         next vertical tab stop.  It
>                                         remains unspecified how
>                                         either party determines or
>                                         establishes where such tab
>                                         stops are located.
>          Form Feed (FF)          12     Moves the printer to the top
>                                         of the next page, keeping
>                                         the same horizontal position.

http://www.rfc-editor.org/rfc/rfc854.txt

I have a solution that I will propose in an upcoming Pull Request.

**Comment by 9swampy** [comment]
Didn't merge but the intent's included in the release 0.9.1 I've just pushed to Nuget.

Any problems, shout.
