### ISSUE TITLE
Assembly does not have a strongname

### ISSUE THREAD

**Issue by T0T4R4** [9swampy/Telnet#43]
I am using you assembly in another assembly project which is COM exposed and requires yours to be signed (have a strong name). Would it be possible for you to sign it ?

**Comment by 9swampy** [comment]
I could but Certificates expire which would cause problems and enforce users to upgrade. In the short term why don't you download the repo and build a signed one for yourself?

**Comment by T0T4R4** [comment]
That's what I did indeed.
