### ISSUE TITLE
Endless loop while logging in

### ISSUE THREAD

**Issue by T0T4R4** [9swampy/Telnet#44]
I am trying your master branch on a Telnet enabled PDU device, and when it goes for login, it endlessly prints out

RollingTimeout exceeded 56:914
RollingTimeout exceeded 56:931
RollingTimeout exceeded 56:945
RollingTimeout exceeded 56:961
RollingTimeout exceeded 56:976
RollingTimeout exceeded 56:992
RollingTimeout exceeded 57:008
RollingTimeout exceeded 57:024
RollingTimeout exceeded 57:039
RollingTimeout exceeded 57:056
RollingTimeout exceeded 57:070
RollingTimeout exceeded 57:087
RollingTimeout exceeded 57:101
RollingTimeout exceeded 57:117
RollingTimeout exceeded 57:133
RollingTimeout exceeded 57:148
RollingTimeout exceeded 57:164
RollingTimeout exceeded 57:180
RollingTimeout exceeded 57:196
RollingTimeout exceeded 57:212
RollingTimeout exceeded 57:226
RollingTimeout exceeded 57:243
RollingTimeout exceeded 57:259

What does this means ?

**Comment by A9G-Data-Droid** [comment]
It means that the PDU is not responding. That's a timeout waiting for Reads from the stream.

**Comment by 9swampy** [comment]
Thx @A9G-Data-Droid
