### ISSUE TITLE
How to set the TerminalType when instantiating new Client?

### ISSUE THREAD

**Issue by BBauer42** [9swampy/Telnet#46]
Is this possible? I see only one mention of it in an issue from 2018. Thanks.

**Comment by A9G-Data-Droid** [comment]
It's possible in the branch I created. I am hardcoding "VT100" because this library can't emulate a more complicated terminal. You are welcome to take my branch and change the Terminal to whatever you want.

https://github.com/A9G-Data-Droid/Telnet/tree/UpdateLiteGuard

**Comment by 9swampy** [comment]
Thx @A9G-Data-Droid. Refer to [](https://github.com/9swampy/Telnet/issues/52#issuecomment-643615695) if you're up for a release/0.9.1
