### ISSUE TITLE
Weird response from server

### ISSUE THREAD

**Issue by ZerGo0** [9swampy/Telnet#51]
Hey,

I'm currently experiencing some issue which might be related to this library. I'm using it to communicate with a local server and send messages back and forward. Every now and then I get very weird responses like this:
![Weird Response](https://i.imgur.com/9qNcQ4M.png)

This is the expected response:
![Normal Response](https://i.imgur.com/lTR4rPD.png)

I'm not 100% sure if this is related to the server or my client. Did anyone else experience anything like this?

**Comment by 9swampy** [comment]
The read will only return what it's been sent, it's not going to make things like that up... must be server.
