### ISSUE TITLE
[Question] Added Telnet Server to main project

### ISSUE THREAD

**Issue by shaggygi** [9swampy/Telnet#54]
Hi.  Came across this recently.  Looks like an interesting API.  I notice you have a TelnetServer implementation in the test projects. 
 Do you have any plans on moving that to the main project where the client class is located?  Thx

**Comment by 9swampy** [comment]
No, it's only an implementation to facilitate Unit Tests. I don't see there being a use case but please elaborate.

**Comment by shaggygi** [comment]
Nothing special.  I have a C-based client and wanted to try it with a server.  When I came across this, thought it might be good to move to this client, as well.
