### ISSUE TITLE
Console.write in TryLoginAsync intentional?

### ISSUE THREAD

**Issue by DOCaCola** [9swampy/Telnet#55]
There is a Console.write command in the NetStandard TerminatedReadAsync implementation. I assume this is a debugging leftover?

**Comment by nyrk** [comment]
I also think so. I'd appreciate if it could be removed 'cause it's quite annoying and undesirable in Console-based apps.

**Comment by wudicgi** [comment]
have the same problem

**Comment by 9swampy** [comment]
Care to submit a PullRequest?
