### ISSUE TITLE
Particular Example Request

### ISSUE THREAD

**Issue by Greyspirit128** [9swampy/Telnet#57]
Would it be possible for an example that doesn't assume logging into a switch and staying connected able to send/receive to the session? I normally only write in Powershell and Arexx so this is a little hard for me.

My particular case is I need to log into a old style telnet BBS (yes BBS) and the username and password prompts are not the first thing that needs to be responded to.  I have to wait for a prompt "Press ENTER". then wait for name and password prompts, entering each. Wait for main menu (with prompt of  "Main>" ignoring Ansi sequences) and then send a command to enter a chat room. What I'm trying to do is extend a Discord IRC relay bot to do a three way with my BBS too. I was able to get logged in using a modified example using System.Net.Sockets but I couldn't figure out how to encapsulate it like the Discord and IRC libraries running in their own parallel threads did so I couldn't send/receive back and forth. Kept giving me object reference errors so I started looking for a Telnet library to try.

**Comment by 9swampy** [comment]
Have to apologise but I'm not quite following your question.

The client establishes a connection, can send and captures responses so you can handle them appropriately. The example on the readme shows how to wait for an expected ">" response, sounds like you just you'd wait for "Press Enter" instead; then continue.
