### ISSUE TITLE
TryLoginAsync attempt 2

### ISSUE THREAD

**Issue by GromitD90** [9swampy/Telnet#60]
Sorry about messing up that last post, as well as accidentally closing it ! Here it is again:

I have a program I wrote that logs in to a Netgear R7000 wireless access point using Prims Telnet. By default the R7000 does not support Telnet but there is a way of enabling it. When enabled my program works without issue. I log in using the TryLoginAsync method, issue the command I want using WriteLine and getting the response to parse using TerminatedReadAsync. I log out using the Dispose method. This sequence is repeated every couple of minutes and has run for weeks without any problems.
My issue is when Telnet is not enabled on the R7000 which can happen if the router has to be rebooted. When this happens my program just hangs on the TryLoginAsync call and will sit there until Telnet is enabled.

I thought that by setting a timeout on the call I would be able to detect this but so far have been unable to get it to work. Here is the code I'm using:
var telnetClient = new PrimS.Telnet.Client(IPaddress, 23, new CancellationToken());
var connection = await telnetClient.TryLoginAsync("root", "rovers15", 20000);
if (telnetClient.IsConnected)
{
      do my thing
}
else
{
    Handle cannot connect event
}

I've tried a few variations on the above but the else condition is never triggered.

Can anyone tell me what I am doing wrong?
TIA
Mike

**Comment by 9swampy** [comment]
Look at the code inside TryLoginAsync; it's just a wrapper for a few consecutive reads/writes. The CancellationToken/Timeout implementation I put in but used minimally and it served my purposes; clearly you've found something that isn't quite right.

**Comment by 9swampy** [comment]
Thanks for coming back and documenting. You've got something that works now so I'll close.
