### ISSUE TITLE
Remove Console.Write() from TerminatedReadAsync

### ISSUE THREAD

**Issue by pascaltippelt** [9swampy/Telnet#63]
Hi!

I am develloping a console application using your library. I parse the return I get from sending a single command to a telnet server. But I don't want to see the response in the console:

https://github.com/9swampy/Telnet/blob/f7bbf01a7fd377862241a4a42a2861c12c4ecd24/PrimS.Telnet.NetStandard/Client.cs#L247-L259

The string is returned anyway, so why always otput the response to the console?

May it be possible to remove this Console.Write() or make it optional?

Best regards

Pascal

**Comment by 9swampy** [comment]
Just did it; included in the release 0.9.1 I've just pushed to Nuget.

Any problems, shout.
