### ISSUE TITLE
TelnetServer?

### ISSUE THREAD

**Issue by GiganteX** [9swampy/Telnet#65]
The example code on the front page (the unit test case) seems broken.
Can't find a TelnetServer class, and the code works fine when I comment that line out.

**Comment by 9swampy** [comment]
[See the actual UnitTest here](https://github.com/9swampy/Telnet/blob/f7bbf01a7fd377862241a4a42a2861c12c4ecd24/PrimS.Telnet.CiTests/WithClient.cs#L169)

The text on the Readme is just missing the appropriate usings to properly reference the namespaces necessary.

Hopefully you got the test to run? You comment suggests you did?

**Comment by GiganteX** [comment]
Ok, I see. Yea I got it to run, thanks.
It was just a bit confusing as I wanted to make a quick test so I took that code and put it in my program and removed the unit test stuff and IntelliSense didn't give me a suggestion for a using for TelnetServer, only the Client...
