### ISSUE TITLE
Guaranteed to Read all text when no terminated string and independently from timeout

### ISSUE THREAD

**Issue by sokolej79** [9swampy/Telnet#66]
I am using Telnet version 0.8.4 and .NET framework 4.6.1.
My program reads files from Windows Ce machine  with Telnet one by one and then save them to local disk and archive folder on Windows CW machine.
Files are csv or txt type and they contain a lot of different texts, so I can not provide termination string.
I also can not rely on timeout when reading file, because they are different sizes from small to big one more than 1 MB, so timeout could terminate read of file text before end of file reached  and text will be truncated.
There is no ReadToEnd method only ReadAsync or TerminatedReadAsync where you must provide timeout.
If file is big or other read command text response has a lot of data you can not rely on timeout because it can happen that read text will be truncated.
My current Telnet command:¸
   
  ```
     var command= "type " + filePath;
     var terminator = "Crg_-1122334455-Crg"; // cannot be in file text response
     await client.WriteLine(command);
     var response = await client.TerminatedReadAsync(terminator, TimeSpan.FromMilliseconds(timeoutMillis));
     if (response.ToLower().Contains("file not found"))
            {
                throw new Exception($"Error read file {filePath}: Error: {response}");
            }
```
Is there an option to guaranteed to read a file to end of text without rely on timeout and termination string?

**Comment by 9swampy** [comment]
Can you magically predict the future? No.

Could a header inform you how much to expect? Yes.

Could you be told "ok you've got it all now, stop listening"? Yes.

The idea's you keep reading until you receive an EOF marker you can recognise or the quantity that you were told to expect. The timeouts are just there to let the code escape when something goes wrong/comms fail.

do
{
  Keep listening for more with a little sanity baked in to how long you wait
} while (!EOF received)

**Comment by sokolej79** [comment]
Thank you very much for your reply and recommendation.
I dont now What is EOF marker if there is none at the end of file based on internal working of Telnet client could be simulated marker with echo command and response of echo be used as termination marker.
Something like that:
 ``
            if (!_client.IsConnected)
            {
                throw new TelnetDisconnectedException($"Error {actionMessage}. Telnet command @{command}. Telnet disconnected.");
            }

            timeoutMillis = 5000;
            terminator = "Crg_110099_Crg";// some unique string that canot be found in response text

            await _client.WriteLine(command);
            await _client.WriteLine($"echo {terminator}"); //!!! echo unique string that will bw used as terminator
 
            var response = await _client.TerminatedReadAsync(terminator, TimeSpan.FromMilliseconds(timeoutMillis));

            if (!response.Contains(terminator)) {
                bool retry = true;
                var repeats = maxRepeats;
                do
                {
                    if (repeats == 0) {
                        throw new Exception($"Read file error. Max repeats read reached. Repeated reads {maxRepeats}.");
                    }

                    if (!_client.IsConnected)
                    {
                        throw new TelnetDisconnectedException($"Error {actionMessage}. Telnet command @{command}. Telnet disconnected.");
                    }

                    var res = await _client.TerminatedReadAsync(terminator, TimeSpan.FromMilliseconds(timeoutMillis));
                    if (!string.IsNullOrWhiteSpace(res))
                    {
                        response += res;
                        if (res.Contains(terminator))
                        {
                            retry = false;
                        }
                    }
                    repeats--;
                } while (retry);
            }

            if (string.IsNullOrWhiteSpace(response))
            {
                throw new Exception($"Error {actionMessage}. Telnet command @{command}. Telnet command response is empty.");
            }
``

**Comment by 9swampy** [comment]
If there is no EOF marker then there's either a header informing how much to expect, or the reader has prior knowledge. That's just how these things work.

Telnet is a very simple and "safe" protocol, it would be hard to do any damage... without malicious intent. However, I suggest you do a bit more research as the solution I proposed would be easier. At a stretch, if you own the code for both client and server negotiate before retrieving the file to find out how much to expect, then retrieve that much.

**Comment by sokolej79** [comment]
Thank you very much for your reply and recommendation.
I must say that otherwise this Telnet package is very good, thank you for this great  package.
I dont own the server only the client.
Server is an old Windows Ce device, which generates csv files and Telnet client reads directory for files, parse file names and read file one by one  with telnet "type "+filepath" command and move it to server archive dir and to client Pc directory, everything with Telnet commands. 
Server (Windows Ce) does not have ftp support and I can only communicate with server with Telnet.
With ordinary HttpClient (Post,Put, get) I can't, it is not working.
I cannot read headers, because Telnet client has only Read methods than return only string, no headers.
Reader has no prior knowledge about how much data to expect for file.
So I dont quite understand how to get information about the file from headers or how would reader have knowledge about how much to expect?

**Comment by 9swampy** [comment]
Maybe `type UninstalItems.log && echo "EOF"` would work?

Substitute "EOF" with something you know cannot be in the file.
