### ISSUE TITLE
Confusing use of Timeout

### ISSUE THREAD

**Issue by hem-bhagat-tark** [9swampy/Telnet#67]
Have a look at this line https://github.com/9swampy/Telnet/blob/master/PrimS.Telnet.NetStandard/ByteStreamHandler.cs#L51, it is doing
`DateTime.Now.Add(TimeSpan.FromMilliseconds(timeout.TotalMilliseconds / 100));`

If we are using Milliseconds in both the TimeSpans, why need to divide by 100? 
The timeout is expected as a parameter in one of the overloads of the Client.ReadAsync. So, this will lead to unexpected behaviour and the user will not know what is happening.

For getting a 3-sec timeout I need to pass 300 sec. Please have a look at this.

**Comment by 9swampy** [comment]
Thanks for the question but behaviour is as intended; your interpretation is not. Reconsider the name of the function you're looking at "ExtendRollingTimeout" and refer to Unit Test covering the intended behaviour "ShouldWaitRoughlyOneTimeout".
