### ISSUE TITLE
Update function TryLoginAsync with Regex terminator string

### ISSUE THREAD

**Issue by crazy9x256** [9swampy/Telnet#70]
Hi team,
I am using Telnet for login to multi vendor device, each vendor has one generic  terminator string, default value terminator is ">".  So Client.TryLoginAsync  return fail with terminator start with "#".
Thanks you ./

**Comment by 9swampy** [comment]
TryLogin is just a convenience, if the "standard" doesn't work for your unit just long hand the correct implementation for your own device.

TerminatedRead & WriteLine with whatever terminators/linefeeds your device expects.
