### ISSUE TITLE
Client keeps disconnecting

### ISSUE THREAD

**Issue by badsgahhl** [9swampy/Telnet#71]
Hey,

I'm trying to use your library. Im trying to built a simple interface where I can use your Client to connect to a telnet server and send multiple commands. However when I initialize the Client directly and instantly use it everything works fine. But if I use the Client and pass it to another class via the constructor and then want to use it there, the TCP connection is already disconnected within milliseconds. Below the code how I use the client. In the debugger I already saw something that made me curious, maybe it has something to do with it. Would be great if you could help out!

```
public class TelnetClientConnection
    {
        private readonly Client _client;

        public TelnetClientConnection(Client client)
        {
            this._client = client;
        }


        public async Task ExecuteCommand()
        {
            Console.WriteLine(command);
            await _client.WriteLineAsync("\x01");
            await _client.WriteLineAsync(command);
        }
    }

    public class TelnetClient
    {
        public async Task<TelnetClientConnection> Connect(CancellationToken cancellationToken)
        {
            using var client = new Client("127.0.0.1", 2121, cancellationToken);

            await client.WriteLineAsync("status");

            return new TelnetClientConnection(client);
        }


    }


```

```
var telnetClient = await new TelnetClient().Connect(stoppingToken);
await telnetClient.ExecuteCommand("connect 172.21.21.83");
```

Debugger Info:
![image](https://user-images.githubusercontent.com/28596891/191913797-0a76dc75-ba60-4fc0-8f08-290aa6ccade0.png)
'((PrimS.Telnet.TcpByteStream)this._client.ByteStream).ReceiveTimeout' threw an exception of type 'System.NullReferenceException'

**Comment by 9swampy** [comment]
Read up on the IDisposable interface.

Your line `using var client = new Client("127.0.0.1", 2121, cancellationToken);` causes the client to be disposed upon return from your Connect method.

You client needs to implement IDisposable and only dispose the client when you're done with it.

**Comment by badsgahhl** [comment]
Works like a charm now. Didn't know about die finally dispose effect of `using`, Thanks for helping out!
