### ISSUE TITLE
How to disable ProactiveOptionNegotiation?

### ISSUE THREAD

**Issue by fraeu** [9swampy/Telnet#79]
Hi there, I've a problem with the command SuppressGoAhead, if i send this command to a device's server, it crash (maybe to a bug in device) 

How can I avoid to send this? Seems that there isn't an option to disable this ProactiveOptionNegotiation

https://github.com/9swampy/Telnet/blob/685992bb2cbd8d214317360be06d135f857f462f/PrimS.Telnet.NetStandard/Client_Config.cs#L87

Thanks

**Comment by 9swampy** [comment]
You can't... or at least you couldn't. I've just pushed a cheeky flag SkipProactiveOptionNegotiation to Client that'll allow you to do so. Let me know if it doesn't help.

**Comment by 9swampy** [comment]
Released in 0.13.0

**Comment by fraeu** [comment]
Thanks, it's work!
