### ISSUE TITLE
TerminatedRead does not behave correctly

### ISSUE THREAD

**Issue by ShehzadNaeem-TMMC** [9swampy/Telnet#80]
TerminatedReadAsync(terminator, timeout) does not actually terminate the read at the inputted termintor character.

For example, when the stream contains the following bytes:
`\n \nXX\r\nYYYY YY YY YYYYYYY YYYYYYYY \"ZZZZ\"\r\n`

and terminated read is called as `await TerminatedReadAsync(PrimS.Telnet.Client.Rfc854LineFeed, ReadTimeout)`

it is expected that only `\n \nXX\r\n` is returned.

Instead the entire contents of the stream is returned.

This is because, in ByteStreamHandlerCancellable line 89, `RetrieveAndParseResponse(sb)` is looped over the entire contents of the stream without checking for the terminator.

The check for the terminator is only done by the calling method in Client.cs line 154 when all the bytes from the stream have already been returned.

Have I misunderstood how this method is supposed to work?

**Comment by 9swampy** [comment]
Your expectation does make sense; but admittedly doesn't align with the current implementation. TerminatedReadAsync was written to anticipate an expected response which would either terminate as expected or not; which would by definition be unanticipated and therefore errant. That said it's a wrapper around ReadAsync that you could poll and parse to deliver the functionality you had expected; and that could be an interesting extension to review on PR. For other's reference; have you resolved in the meantime?

**Comment by ShehzadNaeem-TMMC** [comment]
Thank you for responding. Yes I am using the existing functionality and parsing the stream via regex's for what I need to pull out. The current implementation is not incorrect, it was just unexpected when I used this nice library.

It's good to know that I can always fallback on the ReadAsync to write a custom wrapper in the future to get what I need.

Thanks.
